import type { SwissSongEntry } from './swiss-song-pool'

export const ARCADE_FINALS_SONG_POOL: SwissSongEntry[] = [
  { title: '夏竜 ～Karyu～', oni: 8, ura: 9 },
  { title: 'ボクハシンセ', oni: 8 },
  { title: 'ニジイロバトン', oni: 8 },
  { title: '春竜 ～Haryu～', oni: 8, ura: 9 },
  { title: '仮想現実のテレスコープ', oni: 9, ura: 10 },
  { title: 'オペレート・ミー', oni: 9, ura: 10 },
  { title: 'ラパスの虹', oni: 9, ura: 10 },
  { title: 'パラレルロリポップ', oni: 9 },
  { title: 'ドキドキ胸きゅん おまつりタイム', oni: 9 },
  { title: 'タイコタイム', oni: 9, ura: 10 },
  { title: 'そして勇者は眠りにつく', oni: 9, ura: 10 },
  { title: 'カグツチ', oni: 9 },
  { title: 'オール・イン・マイハート', oni: 9 },
  { title: 'Shiny Kung-fu Revival', oni: 9 },
  { title: 'punk bastards', oni: 9 },
  { title: 'Nosferatu', oni: 9, ura: 10 },
  { title: "Heaven's Rider", oni: 9 },
  { title: 'Amber Light', oni: 9 },
  { title: '彼は誰時の誘惑', oni: 9, ura: 10 },
  { title: '初音ミクの消失‐劇場版‐', oni: 9, ura: 10 },
  { title: '燃えよサファイア', oni: 9 },
  { title: '魔方陣 ‐サモン・デルタ‐', oni: 9 },
  { title: 'LΔchesis', oni: 9, ura: 10 },
  { title: 'モノクロームユートピア', oni: 10 },
  { title: 'トイマチック☆パレード!!', oni: 10 },
  { title: 'デッド・オア・ダイ', oni: 10 },
  { title: 'コネクトカラーズ', oni: 10 },
  { title: 'キャラメル・ジャンキヰ', oni: 10 },
  { title: 'きたさいたま2000', oni: 10 },
  { title: "What's in the box?", oni: 10 },
  { title: '4+1のそれぞれの未来', oni: 10, ura: 10 },
  { title: 'Vixtory', oni: 10, ura: 10 },
  { title: 'VICTORIA', oni: 10 },
  { title: 'UNDEAD HEART(怒りのWarriors)', oni: 10 },
  { title: 'Spectral Rider', oni: 10 },
  { title: 'Soulway', oni: 10 },
  { title: 'SORA-VII シグナスウォール', oni: 10 },
  { title: 'poxei♦︎DOON', oni: 10 },
  { title: "OK I'm blue rat", oni: 10 },
  { title: 'Hurtling Boys', oni: 10 },
  { title: 'CUT! into the FUTURE', oni: 10, ura: 10 },
  { title: '青天の黎明', oni: 10 },
  { title: '憎悪と醜悪の花束', oni: 10, ura: 10 },
  { title: '重金属フューギティブ', oni: 10 },
  { title: '第六天魔王', oni: 10, ura: 10 },
  { title: '赤と白薔薇の魔女', oni: 10 },
  { title: '幽玄ノ乱', oni: 10 },
  { title: '愛と浄罪の森', oni: 10 },
  { title: '神竜 ～Shinryu～', oni: 10, ura: 10 },
  { title: '星河一天', oni: 10 },
  { title: '幕末維新譚', oni: 10 },
  { title: '魑魅魍魎', oni: 10 },
  { title: '冷凍庫CJ ～嗚呼面太鼓ブラザーズ～', oni: 10 },
  { title: '星屑ストラック', oni: 10, ura: 10 },
  { title: '刻竜 ～Kokuryu～', oni: 10, ura: 10 },
  { title: '8OROCHI', oni: 10, ura: 10 },
  { title: '23時54分、陽の旅路へのプレリュード', oni: 10, ura: 10 },
  { title: '≠MM', oni: 10 },
  { title: 'Taiko Drum Monster', oni: 10, ura: 10 },
  { title: 'Behemoth', oni: 10 },
  { title: 'χ談', oni: 10 },
  { title: "Player's High", oni: 10 },
  { title: '月読命', oni: 10 },
  { title: 'カラフル', oni: 10 },
  { title: 'チャーリー ダッシュ！', oni: 10 },
]
