/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as siteRouteRouteImport } from './routes/(site)/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as siteIndexRouteImport } from './routes/(site)/index'
import { Route as siteSongsRouteImport } from './routes/(site)/songs'
import { Route as siteSongPoolRouteImport } from './routes/(site)/song-pool'
import { Route as siteScheduleRouteImport } from './routes/(site)/schedule'
import { Route as siteResultsRouteImport } from './routes/(site)/results'
import { Route as siteContactRouteImport } from './routes/(site)/contact'
import { Route as siteConsoleRouteImport } from './routes/(site)/console'
import { Route as siteArcadeRouteImport } from './routes/(site)/arcade'
import { Route as siteApplyRouteImport } from './routes/(site)/apply'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AdminSettingsRouteRouteImport } from './routes/admin/settings/route'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminTasksIndexRouteImport } from './routes/admin/tasks/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminHelpCenterIndexRouteImport } from './routes/admin/help-center/index'
import { Route as AdminChatsIndexRouteImport } from './routes/admin/chats/index'
import { Route as AdminAppsIndexRouteImport } from './routes/admin/apps/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AdminSettingsNotificationsRouteImport } from './routes/admin/settings/notifications'
import { Route as AdminSettingsDisplayRouteImport } from './routes/admin/settings/display'
import { Route as AdminSettingsAppearanceRouteImport } from './routes/admin/settings/appearance'
import { Route as AdminSettingsAccountRouteImport } from './routes/admin/settings/account'
import { Route as AdminErrorsErrorRouteImport } from './routes/admin/errors/$error'
import { Route as siteOpsArcadeControlRouteImport } from './routes/(site)/ops/arcade-control'
import { Route as siteOpsArcadeBroadcastRouteImport } from './routes/(site)/ops/arcade-broadcast'
import { Route as siteArcadeResults2026IndexRouteImport } from './routes/(site)/arcade-results/2026/index'
import { Route as siteArcadeResults2026FinalsRouteImport } from './routes/(site)/arcade-results/2026/finals'
import { Route as siteArcadeResults2026RegionRouteImport } from './routes/(site)/arcade-results/2026/$region'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const siteRouteRoute = siteRouteRouteImport.update({
  id: '/(site)',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const siteIndexRoute = siteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => siteRouteRoute,
} as any)
const siteSongsRoute = siteSongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => siteRouteRoute,
} as any)
const siteSongPoolRoute = siteSongPoolRouteImport.update({
  id: '/song-pool',
  path: '/song-pool',
  getParentRoute: () => siteRouteRoute,
} as any)
const siteScheduleRoute = siteScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => siteRouteRoute,
} as any)
const siteResultsRoute = siteResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => siteRouteRoute,
} as any)
const siteContactRoute = siteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => siteRouteRoute,
} as any)
const siteConsoleRoute = siteConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => siteRouteRoute,
} as any)
const siteArcadeRoute = siteArcadeRouteImport.update({
  id: '/arcade',
  path: '/arcade',
  getParentRoute: () => siteRouteRoute,
} as any)
const siteApplyRoute = siteApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => siteRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AdminSettingsRouteRoute = AdminSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTasksIndexRoute = AdminTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminHelpCenterIndexRoute = AdminHelpCenterIndexRouteImport.update({
  id: '/help-center/',
  path: '/help-center/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminChatsIndexRoute = AdminChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAppsIndexRoute = AdminAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AdminSettingsNotificationsRoute =
  AdminSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AdminSettingsRouteRoute,
  } as any)
const AdminSettingsDisplayRoute = AdminSettingsDisplayRouteImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsAppearanceRoute = AdminSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsAccountRoute = AdminSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminErrorsErrorRoute = AdminErrorsErrorRouteImport.update({
  id: '/errors/$error',
  path: '/errors/$error',
  getParentRoute: () => AdminRouteRoute,
} as any)
const siteOpsArcadeControlRoute = siteOpsArcadeControlRouteImport.update({
  id: '/ops/arcade-control',
  path: '/ops/arcade-control',
  getParentRoute: () => siteRouteRoute,
} as any)
const siteOpsArcadeBroadcastRoute = siteOpsArcadeBroadcastRouteImport.update({
  id: '/ops/arcade-broadcast',
  path: '/ops/arcade-broadcast',
  getParentRoute: () => siteRouteRoute,
} as any)
const siteArcadeResults2026IndexRoute =
  siteArcadeResults2026IndexRouteImport.update({
    id: '/arcade-results/2026/',
    path: '/arcade-results/2026/',
    getParentRoute: () => siteRouteRoute,
  } as any)
const siteArcadeResults2026FinalsRoute =
  siteArcadeResults2026FinalsRouteImport.update({
    id: '/arcade-results/2026/finals',
    path: '/arcade-results/2026/finals',
    getParentRoute: () => siteRouteRoute,
  } as any)
const siteArcadeResults2026RegionRoute =
  siteArcadeResults2026RegionRouteImport.update({
    id: '/arcade-results/2026/$region',
    path: '/arcade-results/2026/$region',
    getParentRoute: () => siteRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/apply': typeof siteApplyRoute
  '/arcade': typeof siteArcadeRoute
  '/console': typeof siteConsoleRoute
  '/contact': typeof siteContactRoute
  '/results': typeof siteResultsRoute
  '/schedule': typeof siteScheduleRoute
  '/song-pool': typeof siteSongPoolRoute
  '/songs': typeof siteSongsRoute
  '/': typeof siteIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/ops/arcade-broadcast': typeof siteOpsArcadeBroadcastRoute
  '/ops/arcade-control': typeof siteOpsArcadeControlRoute
  '/admin/errors/$error': typeof AdminErrorsErrorRoute
  '/admin/settings/account': typeof AdminSettingsAccountRoute
  '/admin/settings/appearance': typeof AdminSettingsAppearanceRoute
  '/admin/settings/display': typeof AdminSettingsDisplayRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/admin/apps': typeof AdminAppsIndexRoute
  '/admin/chats': typeof AdminChatsIndexRoute
  '/admin/help-center': typeof AdminHelpCenterIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/tasks': typeof AdminTasksIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/arcade-results/2026/$region': typeof siteArcadeResults2026RegionRoute
  '/arcade-results/2026/finals': typeof siteArcadeResults2026FinalsRoute
  '/arcade-results/2026': typeof siteArcadeResults2026IndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/apply': typeof siteApplyRoute
  '/arcade': typeof siteArcadeRoute
  '/console': typeof siteConsoleRoute
  '/contact': typeof siteContactRoute
  '/results': typeof siteResultsRoute
  '/schedule': typeof siteScheduleRoute
  '/song-pool': typeof siteSongPoolRoute
  '/songs': typeof siteSongsRoute
  '/': typeof siteIndexRoute
  '/admin': typeof AdminIndexRoute
  '/ops/arcade-broadcast': typeof siteOpsArcadeBroadcastRoute
  '/ops/arcade-control': typeof siteOpsArcadeControlRoute
  '/admin/errors/$error': typeof AdminErrorsErrorRoute
  '/admin/settings/account': typeof AdminSettingsAccountRoute
  '/admin/settings/appearance': typeof AdminSettingsAppearanceRoute
  '/admin/settings/display': typeof AdminSettingsDisplayRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/admin/apps': typeof AdminAppsIndexRoute
  '/admin/chats': typeof AdminChatsIndexRoute
  '/admin/help-center': typeof AdminHelpCenterIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/tasks': typeof AdminTasksIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/arcade-results/2026/$region': typeof siteArcadeResults2026RegionRoute
  '/arcade-results/2026/finals': typeof siteArcadeResults2026FinalsRoute
  '/arcade-results/2026': typeof siteArcadeResults2026IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(site)': typeof siteRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/(site)/apply': typeof siteApplyRoute
  '/(site)/arcade': typeof siteArcadeRoute
  '/(site)/console': typeof siteConsoleRoute
  '/(site)/contact': typeof siteContactRoute
  '/(site)/results': typeof siteResultsRoute
  '/(site)/schedule': typeof siteScheduleRoute
  '/(site)/song-pool': typeof siteSongPoolRoute
  '/(site)/songs': typeof siteSongsRoute
  '/(site)/': typeof siteIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/(site)/ops/arcade-broadcast': typeof siteOpsArcadeBroadcastRoute
  '/(site)/ops/arcade-control': typeof siteOpsArcadeControlRoute
  '/admin/errors/$error': typeof AdminErrorsErrorRoute
  '/admin/settings/account': typeof AdminSettingsAccountRoute
  '/admin/settings/appearance': typeof AdminSettingsAppearanceRoute
  '/admin/settings/display': typeof AdminSettingsDisplayRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/admin/apps/': typeof AdminAppsIndexRoute
  '/admin/chats/': typeof AdminChatsIndexRoute
  '/admin/help-center/': typeof AdminHelpCenterIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/tasks/': typeof AdminTasksIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/(site)/arcade-results/2026/$region': typeof siteArcadeResults2026RegionRoute
  '/(site)/arcade-results/2026/finals': typeof siteArcadeResults2026FinalsRoute
  '/(site)/arcade-results/2026/': typeof siteArcadeResults2026IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/clerk'
    | '/admin/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/apply'
    | '/arcade'
    | '/console'
    | '/contact'
    | '/results'
    | '/schedule'
    | '/song-pool'
    | '/songs'
    | '/'
    | '/admin/'
    | '/ops/arcade-broadcast'
    | '/ops/arcade-control'
    | '/admin/errors/$error'
    | '/admin/settings/account'
    | '/admin/settings/appearance'
    | '/admin/settings/display'
    | '/admin/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/admin/apps'
    | '/admin/chats'
    | '/admin/help-center'
    | '/admin/settings/'
    | '/admin/tasks'
    | '/admin/users'
    | '/arcade-results/2026/$region'
    | '/arcade-results/2026/finals'
    | '/arcade-results/2026'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/apply'
    | '/arcade'
    | '/console'
    | '/contact'
    | '/results'
    | '/schedule'
    | '/song-pool'
    | '/songs'
    | '/'
    | '/admin'
    | '/ops/arcade-broadcast'
    | '/ops/arcade-control'
    | '/admin/errors/$error'
    | '/admin/settings/account'
    | '/admin/settings/appearance'
    | '/admin/settings/display'
    | '/admin/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/admin/apps'
    | '/admin/chats'
    | '/admin/help-center'
    | '/admin/settings'
    | '/admin/tasks'
    | '/admin/users'
    | '/arcade-results/2026/$region'
    | '/arcade-results/2026/finals'
    | '/arcade-results/2026'
  id:
    | '__root__'
    | '/(site)'
    | '/admin'
    | '/clerk'
    | '/admin/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/(site)/apply'
    | '/(site)/arcade'
    | '/(site)/console'
    | '/(site)/contact'
    | '/(site)/results'
    | '/(site)/schedule'
    | '/(site)/song-pool'
    | '/(site)/songs'
    | '/(site)/'
    | '/admin/'
    | '/(site)/ops/arcade-broadcast'
    | '/(site)/ops/arcade-control'
    | '/admin/errors/$error'
    | '/admin/settings/account'
    | '/admin/settings/appearance'
    | '/admin/settings/display'
    | '/admin/settings/notifications'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/admin/apps/'
    | '/admin/chats/'
    | '/admin/help-center/'
    | '/admin/settings/'
    | '/admin/tasks/'
    | '/admin/users/'
    | '/(site)/arcade-results/2026/$region'
    | '/(site)/arcade-results/2026/finals'
    | '/(site)/arcade-results/2026/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  siteRouteRoute: typeof siteRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(site)': {
      id: '/(site)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof siteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(site)/': {
      id: '/(site)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof siteIndexRouteImport
      parentRoute: typeof siteRouteRoute
    }
    '/(site)/songs': {
      id: '/(site)/songs'
      path: '/songs'
      fullPath: '/songs'
      preLoaderRoute: typeof siteSongsRouteImport
      parentRoute: typeof siteRouteRoute
    }
    '/(site)/song-pool': {
      id: '/(site)/song-pool'
      path: '/song-pool'
      fullPath: '/song-pool'
      preLoaderRoute: typeof siteSongPoolRouteImport
      parentRoute: typeof siteRouteRoute
    }
    '/(site)/schedule': {
      id: '/(site)/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof siteScheduleRouteImport
      parentRoute: typeof siteRouteRoute
    }
    '/(site)/results': {
      id: '/(site)/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof siteResultsRouteImport
      parentRoute: typeof siteRouteRoute
    }
    '/(site)/contact': {
      id: '/(site)/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof siteContactRouteImport
      parentRoute: typeof siteRouteRoute
    }
    '/(site)/console': {
      id: '/(site)/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof siteConsoleRouteImport
      parentRoute: typeof siteRouteRoute
    }
    '/(site)/arcade': {
      id: '/(site)/arcade'
      path: '/arcade'
      fullPath: '/arcade'
      preLoaderRoute: typeof siteArcadeRouteImport
      parentRoute: typeof siteRouteRoute
    }
    '/(site)/apply': {
      id: '/(site)/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof siteApplyRouteImport
      parentRoute: typeof siteRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tasks/': {
      id: '/admin/tasks/'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/help-center/': {
      id: '/admin/help-center/'
      path: '/help-center'
      fullPath: '/admin/help-center'
      preLoaderRoute: typeof AdminHelpCenterIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/chats/': {
      id: '/admin/chats/'
      path: '/chats'
      fullPath: '/admin/chats'
      preLoaderRoute: typeof AdminChatsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/apps/': {
      id: '/admin/apps/'
      path: '/apps'
      fullPath: '/admin/apps'
      preLoaderRoute: typeof AdminAppsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/admin/settings/notifications': {
      id: '/admin/settings/notifications'
      path: '/notifications'
      fullPath: '/admin/settings/notifications'
      preLoaderRoute: typeof AdminSettingsNotificationsRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/display': {
      id: '/admin/settings/display'
      path: '/display'
      fullPath: '/admin/settings/display'
      preLoaderRoute: typeof AdminSettingsDisplayRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/appearance': {
      id: '/admin/settings/appearance'
      path: '/appearance'
      fullPath: '/admin/settings/appearance'
      preLoaderRoute: typeof AdminSettingsAppearanceRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/account': {
      id: '/admin/settings/account'
      path: '/account'
      fullPath: '/admin/settings/account'
      preLoaderRoute: typeof AdminSettingsAccountRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/errors/$error': {
      id: '/admin/errors/$error'
      path: '/errors/$error'
      fullPath: '/admin/errors/$error'
      preLoaderRoute: typeof AdminErrorsErrorRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(site)/ops/arcade-control': {
      id: '/(site)/ops/arcade-control'
      path: '/ops/arcade-control'
      fullPath: '/ops/arcade-control'
      preLoaderRoute: typeof siteOpsArcadeControlRouteImport
      parentRoute: typeof siteRouteRoute
    }
    '/(site)/ops/arcade-broadcast': {
      id: '/(site)/ops/arcade-broadcast'
      path: '/ops/arcade-broadcast'
      fullPath: '/ops/arcade-broadcast'
      preLoaderRoute: typeof siteOpsArcadeBroadcastRouteImport
      parentRoute: typeof siteRouteRoute
    }
    '/(site)/arcade-results/2026/': {
      id: '/(site)/arcade-results/2026/'
      path: '/arcade-results/2026'
      fullPath: '/arcade-results/2026'
      preLoaderRoute: typeof siteArcadeResults2026IndexRouteImport
      parentRoute: typeof siteRouteRoute
    }
    '/(site)/arcade-results/2026/finals': {
      id: '/(site)/arcade-results/2026/finals'
      path: '/arcade-results/2026/finals'
      fullPath: '/arcade-results/2026/finals'
      preLoaderRoute: typeof siteArcadeResults2026FinalsRouteImport
      parentRoute: typeof siteRouteRoute
    }
    '/(site)/arcade-results/2026/$region': {
      id: '/(site)/arcade-results/2026/$region'
      path: '/arcade-results/2026/$region'
      fullPath: '/arcade-results/2026/$region'
      preLoaderRoute: typeof siteArcadeResults2026RegionRouteImport
      parentRoute: typeof siteRouteRoute
    }
  }
}

interface siteRouteRouteChildren {
  siteApplyRoute: typeof siteApplyRoute
  siteArcadeRoute: typeof siteArcadeRoute
  siteConsoleRoute: typeof siteConsoleRoute
  siteContactRoute: typeof siteContactRoute
  siteResultsRoute: typeof siteResultsRoute
  siteScheduleRoute: typeof siteScheduleRoute
  siteSongPoolRoute: typeof siteSongPoolRoute
  siteSongsRoute: typeof siteSongsRoute
  siteIndexRoute: typeof siteIndexRoute
  siteOpsArcadeBroadcastRoute: typeof siteOpsArcadeBroadcastRoute
  siteOpsArcadeControlRoute: typeof siteOpsArcadeControlRoute
  siteArcadeResults2026RegionRoute: typeof siteArcadeResults2026RegionRoute
  siteArcadeResults2026FinalsRoute: typeof siteArcadeResults2026FinalsRoute
  siteArcadeResults2026IndexRoute: typeof siteArcadeResults2026IndexRoute
}

const siteRouteRouteChildren: siteRouteRouteChildren = {
  siteApplyRoute: siteApplyRoute,
  siteArcadeRoute: siteArcadeRoute,
  siteConsoleRoute: siteConsoleRoute,
  siteContactRoute: siteContactRoute,
  siteResultsRoute: siteResultsRoute,
  siteScheduleRoute: siteScheduleRoute,
  siteSongPoolRoute: siteSongPoolRoute,
  siteSongsRoute: siteSongsRoute,
  siteIndexRoute: siteIndexRoute,
  siteOpsArcadeBroadcastRoute: siteOpsArcadeBroadcastRoute,
  siteOpsArcadeControlRoute: siteOpsArcadeControlRoute,
  siteArcadeResults2026RegionRoute: siteArcadeResults2026RegionRoute,
  siteArcadeResults2026FinalsRoute: siteArcadeResults2026FinalsRoute,
  siteArcadeResults2026IndexRoute: siteArcadeResults2026IndexRoute,
}

const siteRouteRouteWithChildren = siteRouteRoute._addFileChildren(
  siteRouteRouteChildren,
)

interface AdminSettingsRouteRouteChildren {
  AdminSettingsAccountRoute: typeof AdminSettingsAccountRoute
  AdminSettingsAppearanceRoute: typeof AdminSettingsAppearanceRoute
  AdminSettingsDisplayRoute: typeof AdminSettingsDisplayRoute
  AdminSettingsNotificationsRoute: typeof AdminSettingsNotificationsRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
}

const AdminSettingsRouteRouteChildren: AdminSettingsRouteRouteChildren = {
  AdminSettingsAccountRoute: AdminSettingsAccountRoute,
  AdminSettingsAppearanceRoute: AdminSettingsAppearanceRoute,
  AdminSettingsDisplayRoute: AdminSettingsDisplayRoute,
  AdminSettingsNotificationsRoute: AdminSettingsNotificationsRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
}

const AdminSettingsRouteRouteWithChildren =
  AdminSettingsRouteRoute._addFileChildren(AdminSettingsRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminSettingsRouteRoute: typeof AdminSettingsRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminErrorsErrorRoute: typeof AdminErrorsErrorRoute
  AdminAppsIndexRoute: typeof AdminAppsIndexRoute
  AdminChatsIndexRoute: typeof AdminChatsIndexRoute
  AdminHelpCenterIndexRoute: typeof AdminHelpCenterIndexRoute
  AdminTasksIndexRoute: typeof AdminTasksIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminSettingsRouteRoute: AdminSettingsRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminErrorsErrorRoute: AdminErrorsErrorRoute,
  AdminAppsIndexRoute: AdminAppsIndexRoute,
  AdminChatsIndexRoute: AdminChatsIndexRoute,
  AdminHelpCenterIndexRoute: AdminHelpCenterIndexRoute,
  AdminTasksIndexRoute: AdminTasksIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  siteRouteRoute: siteRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
